# Generated by Django 2.1.1 on 2018-09-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='now1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
